/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_management_system;

import javax.swing.JFrame;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import projects.select;
import projects.*;

/**
 *
 * @author USER
 */
public class CustomerCheckin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerCheckin.class.getName());
    
    

    /**
     * Creates new form CostumerCheckout
     */
    public CustomerCheckin() {
       initComponents();
       this.setLocationRelativeTo(null);
       
       txtCheckInDate.setEditable(false);
       txtPricePerDay.setEditable(false);
       SimpleDateFormat myFormat =new SimpleDateFormat("yyyy/MM/dd");
       Calendar cal=Calendar.getInstance();
       txtCheckInDate.setText(myFormat.format(cal.getTime()));
        
    }
    
    String BedType;
    String RoomType;
    String RoomNumber;
    String PricePerDay;
    
    public void roomDetails(){
        
    comboRoomNumber.removeAllItems();
    txtPricePerDay.setText("");
    
    BedType = (String) comboBedType.getSelectedItem();
    RoomType = (String) comboRoomType.getSelectedItem();
    
    try {
        String query = "SELECT * FROM manageroom WHERE BedType = '" + BedType + 
                       "' AND RoomType = '" + RoomType + 
                       "' AND Status = 'Not Booked'";
        
        ResultSet rs = select.getData(query);
        
        if (rs != null) {
            while (rs.next()) {
                comboRoomNumber.addItem(rs.getString("RoomNumber")); 
            }
        } else {
            JOptionPane.showMessageDialog(null, "No data found.");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtMobileNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNationality = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtCheckInDate = new javax.swing.JTextField();
        txtPricePerDay = new javax.swing.JTextField();
        comboRoomNumber = new javax.swing.JComboBox<>();
        comboRoomType = new javax.swing.JComboBox<>();
        comboBedType = new javax.swing.JComboBox<>();
        comboGender1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnCheckIn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Costumer Checkin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 22, 351, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 97, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 184, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 259, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 346, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 514, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Check In Date(Today)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 97, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Room Type");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 184, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bed");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 259, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Room Number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 346, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 427, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nationality");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 427, -1, -1));

        txtName.setBackground(new java.awt.Color(204, 204, 204));
        txtName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 135, 519, -1));

        txtMobileNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtMobileNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 222, 519, -1));

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 297, 519, -1));

        txtNationality.setBackground(new java.awt.Color(204, 204, 204));
        txtNationality.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 471, 519, -1));

        txtAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 552, 519, -1));

        txtCheckInDate.setBackground(new java.awt.Color(204, 204, 204));
        txtCheckInDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtCheckInDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 135, 519, -1));

        txtPricePerDay.setBackground(new java.awt.Color(204, 204, 204));
        txtPricePerDay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtPricePerDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 471, 519, -1));

        comboRoomNumber.setBackground(new java.awt.Color(204, 204, 204));
        comboRoomNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboRoomNumber.setForeground(new java.awt.Color(0, 0, 0));
        comboRoomNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboRoomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRoomNumberActionPerformed(evt);
            }
        });
        getContentPane().add(comboRoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 377, 519, -1));

        comboRoomType.setBackground(new java.awt.Color(204, 204, 204));
        comboRoomType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboRoomType.setForeground(new java.awt.Color(0, 0, 0));
        comboRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON AC" }));
        comboRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRoomTypeActionPerformed(evt);
            }
        });
        getContentPane().add(comboRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 222, 519, -1));

        comboBedType.setBackground(new java.awt.Color(204, 204, 204));
        comboBedType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboBedType.setForeground(new java.awt.Color(0, 0, 0));
        comboBedType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        comboBedType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBedTypeActionPerformed(evt);
            }
        });
        getContentPane().add(comboBedType, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 297, 519, -1));

        comboGender1.setBackground(new java.awt.Color(204, 204, 204));
        comboGender1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboGender1.setForeground(new java.awt.Color(0, 0, 0));
        comboGender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(comboGender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 377, 519, -1));

        jPanel1.setBackground(new java.awt.Color(40, 50, 40));

        btnCheckIn.setBackground(new java.awt.Color(100, 149, 237));
        btnCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCheckIn.setForeground(new java.awt.Color(240, 240, 240));
        btnCheckIn.setText("Check In Now");
        btnCheckIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        cancelbtn.setBackground(new java.awt.Color(100, 149, 237));
        cancelbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelbtn.setForeground(new java.awt.Color(240, 240, 240));
        cancelbtn.setText("Cancel");
        cancelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(926, Short.MAX_VALUE)
                .addComponent(btnCheckIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelbtn)
                .addGap(455, 455, 455))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(532, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckIn)
                    .addComponent(cancelbtn))
                .addGap(206, 206, 206))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbtnMouseClicked
        // TODO add your handling code here:
        HomePage hp = new HomePage();
        hp.setLocationRelativeTo(null);
        hp.pack();
        hp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        hp.setVisible(true);
              
        
    }//GEN-LAST:event_cancelbtnMouseClicked

    private void comboBedTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBedTypeActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_comboBedTypeActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        // TODO add your handling code here:
        int Id=1;
        String Name = txtName.getText();
        String MobileNumber = txtMobileNumber.getText();
        String Email = txtEmail.getText();
        String Gender =(String)comboGender1.getSelectedItem();
        String Nationality = txtNationality.getText();
        String Address = txtAddress.getText();
        String CheckInDate = txtCheckInDate.getText();
        String RoomType = (String)comboRoomType.getSelectedItem();
        String Bed = (String)comboBedType.getSelectedItem();
        String RoomNumber = (String)comboRoomNumber.getSelectedItem();
        String PricePerDay = txtPricePerDay.getText();
        String Query = "select max(Id) from checkin";
        try{
            ResultSet rs = select.getData(Query);
            while(rs.next()){
                Id=rs.getInt(1);
                Id=Id+1;
                
                if(!PricePerDay.equals("")){
                    Query = "update manageroom set status='Booked' where RoomNumber='"+RoomNumber+"'";
                    InsertUpdateDelete.setData(Query,"");
                    Query = "insert into checkin(Id,Name,MobileNumber,Email,Gender,Nationality,Address,CheckInDate,RoomType,Bed,RoomNumber,PricePerDay) values('"+Id+"','"+Name+"','"+MobileNumber+"','"+Email+"','"+Gender+"','"+Nationality+"','"+Address+"','"+CheckInDate+"','"+RoomType+"','"+Bed+"','"+RoomNumber+"','"+PricePerDay+"')";
                    InsertUpdateDelete.setData(Query, "Customer Check In Successfully");
                    setVisible(false);
                    new CustomerCheckin().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Please complete all fields");
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void comboRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRoomTypeActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_comboRoomTypeActionPerformed

    private void comboRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRoomNumberActionPerformed
        // TODO add your handling code here:
        RoomNumber=(String)comboRoomNumber.getSelectedItem();
        try{
            ResultSet rs=select.getData("select *from manageroom where roomnumber='"+RoomNumber+"'");
            while(rs.next()){
                txtPricePerDay.setText(rs.getString(4));
            }
        }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_comboRoomNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerCheckin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JComboBox<String> comboBedType;
    private javax.swing.JComboBox<String> comboGender1;
    private javax.swing.JComboBox<String> comboRoomNumber;
    private javax.swing.JComboBox<String> comboRoomType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCheckInDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtPricePerDay;
    // End of variables declaration//GEN-END:variables
}
