/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_management_system;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import javax.swing.JFrame;
import javax.swing.JFrame;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import projects.*;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;

/**
 *
 * @author USER
 */
public class CustomerCheckout extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerCheckout.class.getName());

    /**
     * Creates new form CostumerCheckout
     */
    public CustomerCheckout() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        txtCustomerName.setEditable(false);
        txtCheckInDate.setEditable(false);
        txtCheckOutDate.setEditable(false);
        txtMobileNumber.setEditable(false);
        txtPricePerDay.setEditable(false);
        txtNumberOfDays.setEditable(false);
        txtAmount.setEditable(false);
        txtEmail.setEditable(false);
    }
    
    int Id = 0;
    String Query;
    String RoomType;
    String BedType;
    String RoomNumber;

    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPricePerDay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCheckInDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRoomNumber = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        txtNumberOfDays = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCheckOutDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        checkOutTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cancelbtn = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Checkout");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 16, 351, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 162, -1, -1));

        txtCustomerName.setBackground(new java.awt.Color(204, 204, 204));
        txtCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 206, 215, 34));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price  Per day");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 247, -1, -1));

        txtPricePerDay.setBackground(new java.awt.Color(204, 204, 204));
        txtPricePerDay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtPricePerDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 278, 215, 34));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Check in Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 324, -1, -1));

        txtCheckInDate.setBackground(new java.awt.Color(204, 204, 204));
        txtCheckInDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCheckInDate.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCheckInDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 355, 215, 35));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Room Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 61, -1, -1));

        txtRoomNumber.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtRoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 57, 129, 38));

        btnSearch.setBackground(new java.awt.Color(100, 149, 237));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(240, 240, 240));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 57, -1, 38));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customer Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 162, -1, -1));

        txtMobileNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtMobileNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 207, 271, 30));

        txtNumberOfDays.setBackground(new java.awt.Color(204, 204, 204));
        txtNumberOfDays.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtNumberOfDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 278, 271, 34));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Number Of Days");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 247, -1, -1));

        txtCheckOutDate.setBackground(new java.awt.Color(204, 204, 204));
        txtCheckOutDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtCheckOutDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 355, 271, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Check Out Date (Today)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 324, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 162, -1, -1));

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 205, 358, 36));

        jLabel10.setBackground(new java.awt.Color(0, 51, 51));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Amount to Collect From Customer");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 247, -1, -1));

        txtAmount.setBackground(new java.awt.Color(204, 204, 204));
        txtAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 278, 358, 34));

        checkOutTable.setBackground(new java.awt.Color(204, 204, 204));
        checkOutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Mobile Number", "Email ID", "Gender", "Nationality", "Address", "Check In Date", "Room Type", "Bed", "Room Number", "Price Per Day"
            }
        ));
        jScrollPane1.setViewportView(checkOutTable);
        if (checkOutTable.getColumnModel().getColumnCount() > 0) {
            checkOutTable.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 438, 1238, 320));

        jPanel1.setBackground(new java.awt.Color(40, 50, 40));

        cancelbtn.setBackground(new java.awt.Color(100, 149, 237));
        cancelbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelbtn.setForeground(new java.awt.Color(240, 240, 240));
        cancelbtn.setText("Cancel");
        cancelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelbtnMouseClicked(evt);
            }
        });
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(100, 149, 237));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(240, 240, 240));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCheckOut.setBackground(new java.awt.Color(100, 149, 237));
        btnCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCheckOut.setForeground(new java.awt.Color(240, 240, 240));
        btnCheckOut.setText("Check Out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(1006, Short.MAX_VALUE)
                .addComponent(btnCheckOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(394, 394, 394))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerCheckout().setVisible(true);
              
         
    }//GEN-LAST:event_btnClearActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void cancelbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbtnMouseClicked
        // TODO add your handling code here:
        HomePage hp = new HomePage();
           hp.setLocationRelativeTo(null);
           hp.pack();
           hp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           hp.setVisible(true);
           
    }//GEN-LAST:event_cancelbtnMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String RoomNumber = txtRoomNumber.getText();
        try{
            ResultSet rs = select.getData("select *from checkin where RoomNumber='"+RoomNumber+"' and checkout is NULL");
            if(rs.next()){
                txtRoomNumber.setEditable(false);
                Id = rs.getInt(1);
                txtCustomerName.setText(rs.getString(2));
                txtCheckInDate.setText(rs.getString(8));
                txtMobileNumber.setText(rs.getString(3));
                txtPricePerDay.setText(rs.getString(12));
                
                
                
                SimpleDateFormat myFormat = new SimpleDateFormat("yyy/MM/dd");
                Calendar cal=Calendar.getInstance();
                txtCheckOutDate.setText(myFormat.format(cal.getTime()));
                String dateBeforeString=rs.getString(8);
                java.util.Date dateBefore=myFormat.parse(dateBeforeString);
                String dateAfterString=myFormat.format(cal.getTime());
                java.util.Date dateAfter=myFormat.parse(dateAfterString);
                long difference=dateAfter.getTime() - dateBefore.getTime();
                int NumberOfDayStay=(int) (difference/(1000*60*60*24));
                if(NumberOfDayStay==0){
                    NumberOfDayStay=1;
                    txtNumberOfDays.setText(String.valueOf(NumberOfDayStay));
                    float price = Float.parseFloat(txtPricePerDay.getText());
                    
                    txtAmount.setText(String.valueOf(NumberOfDayStay*price));
                    txtEmail.setText(rs.getString(4));
                    RoomType = rs.getString(9);
                    BedType = rs.getString(10);
                } else {
                    JOptionPane.showMessageDialog(null, "Room Number is not Booked or Room Number Does Not Exist");
                }
                
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
   
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        String customername = txtCustomerName.getText();
          String customermobile = txtMobileNumber.getText();
          String email = txtEmail.getText();
          
          String CheckOut = txtCheckOutDate.getText();
          String NumberofDayStay = txtNumberOfDays.getText();
          String TotalAmount = txtAmount.getText();
          RoomNumber = txtRoomNumber.getText();
          Query = "update checkin set numberofdaystay='"+NumberofDayStay+"', totalamount='"+TotalAmount+"', checkout='"+CheckOut+"' where Id='"+Id+"'";
          InsertUpdateDelete.setData(Query, "");
          Query = "update manageroom set Status='Not Booked' where RoomNumber='"+RoomNumber+"'";
          InsertUpdateDelete.setData(Query, "");
          String path = "C:\\Users\\USER\\OneDrive\\Documents\\";
          com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
          try{
              PdfWriter.getInstance(doc, new FileOutputStream(path+""+Id+".pdf"));
              doc.open();
              Paragraph paragraph1= new Paragraph("                                  Hotel Management System Receipt                                  ");
              doc.add(paragraph1);
              Paragraph paragraph2 = new Paragraph("**************************************************************************************************");
              doc.add(paragraph2);
              Paragraph paragraph3 = new Paragraph("\tBill ID: "+Id+"\nName: "+customername+"\nMobile Number: "+customermobile+"\nEmail: "+email+"\n");
              doc.add(paragraph3);
              doc.add(paragraph2);
              Paragraph paragraph4 = new Paragraph("\tRoom Details:\nNumber: "+txtRoomNumber.getText()+"\nType: "+RoomType+"\nBed: "+BedType+"\nPrice Per Day: "+txtPricePerDay.getText()+"");
              doc.add(paragraph4);
              doc.add(paragraph2);
              PdfPTable tbl=new PdfPTable(4);
              tbl.addCell("Check IN Date: " + txtCheckInDate.getText());
              tbl.addCell("Check Out Date: " + txtCheckOutDate.getText());
              tbl.addCell("Number Of day Stay: " + txtNumberOfDays.getText());
              tbl.addCell("Total Amount Paid: " + TotalAmount);
              doc.add(tbl);
              doc.add(paragraph2);
              Paragraph paragraph5 = new Paragraph("Thank you, Please Visit Again.");
              doc.add(paragraph5);
              
          } catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
          }
          doc.close();
          int a = JOptionPane.showConfirmDialog(null, "Do you want to Print Bill","Select",JOptionPane.YES_NO_OPTION);
          if(a==0)
          { 
              try
              {
                 if((new File("C:\\Users\\USER\\OneDrive\\Documents\\"+Id+".pdf")).exists())
                 {
                    Process p = Runtime
                            .getRuntime()
                            .exec("rundll32 url.dll,FileProtocolHandler C:\\Users\\USER\\OneDrive\\Documents\\"+Id+".pdf");
                 }
                 else
                 {
                     System.out.println("File is not Exists");
                     
                 }
              }
              catch(Exception e)
              {
                 JOptionPane.showMessageDialog(null, e);
                 
              }
          }
          setVisible(false);
          new CustomerCheckout().setVisible(true);
        
     
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs = select.getData("select *from checkin where checkout is NULL");
        DefaultTableModel model = (DefaultTableModel)checkOutTable.getModel();
        try{
            while(rs.next()){
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12)});
                
            }
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerCheckout().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JTable checkOutTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCheckInDate;
    private javax.swing.JTextField txtCheckOutDate;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtNumberOfDays;
    private javax.swing.JTextField txtPricePerDay;
    private javax.swing.JTextField txtRoomNumber;
    // End of variables declaration//GEN-END:variables
}
