/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_management_system;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class HomePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    /**
     * Creates new form HomePage
     */
    public HomePage() {
       initComponents();
       this.setLocationRelativeTo(null);
       
       setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JLabel();
        btnManageRoom = new javax.swing.JButton();
        CostumerCheckin = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(204, 0, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_management_system/button (2).png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1870, 10, -1, -1));

        btnManageRoom.setBackground(new java.awt.Color(255, 255, 255));
        btnManageRoom.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnManageRoom.setForeground(new java.awt.Color(0, 0, 0));
        btnManageRoom.setText("Manage Room");
        btnManageRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 300, -1));

        CostumerCheckin.setBackground(new java.awt.Color(255, 255, 255));
        CostumerCheckin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CostumerCheckin.setForeground(new java.awt.Color(0, 0, 0));
        CostumerCheckin.setText("Costumer Checkin");
        CostumerCheckin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CostumerCheckin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CostumerCheckinMouseClicked(evt);
            }
        });
        CostumerCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostumerCheckinActionPerformed(evt);
            }
        });
        getContentPane().add(CostumerCheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 380, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Costumer Checkout");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 370, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Costumer Bill Details");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 30, 380, -1));

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(153, 0, 0));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_management_system/logout.png"))); // NOI18N
        btnLogOut.setText("Logout");
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 990, 250, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_management_system/HomePagheBGS.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        JOptionPane.showMessageDialog(this, "Please confirm if you want to log out");
        login abc = new login();
        abc.setLocationRelativeTo(null);
        abc.pack();
        abc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        abc.setVisible(true);
        
        
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnManageRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRoomActionPerformed
        ManageRoom mgr = new ManageRoom();
        mgr.setLocationRelativeTo(null);
        mgr.pack();
        mgr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mgr.setVisible(true);
         
        
        
    }//GEN-LAST:event_btnManageRoomActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void CostumerCheckinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CostumerCheckinMouseClicked
        // TODO add your handling code here:
        CustomerCheckin cc = new CustomerCheckin();
        cc.setLocationRelativeTo(null);
        cc.pack();
        cc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cc.setVisible(true);
        
        
        
    }//GEN-LAST:event_CostumerCheckinMouseClicked

    private void CostumerCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostumerCheckinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostumerCheckinActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        CustomerCheckout co = new CustomerCheckout();
        co.setLocationRelativeTo(null);
        co.pack();
        co.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        co.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        CustomerBillDetails cbd = new CustomerBillDetails();
        cbd.setLocationRelativeTo(null);
        cbd.pack();
        cbd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cbd.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CostumerCheckin;
    private javax.swing.JLabel btnExit;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageRoom;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
