/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_management_system;

import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author USER
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
  
    Accounts Account = new Accounts();
    
    String edceluser = Account.getEdcelUser();
    String edcelpass = Account.getEdcelPass();
    
    String newUser = Account.getUser();
    String newPass = Account.getPass();
   
    
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JUsername = new javax.swing.JTextField();
        btnExit = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnsSignin = new javax.swing.JButton();
        jLabelShow_Password = new javax.swing.JCheckBox();
        JPassword = new javax.swing.JPasswordField();
        GoBackbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 540));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_management_system/account.png"))); // NOI18N
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 530, -1, -1));

        JUsername.setBackground(new java.awt.Color(255, 255, 255));
        JUsername.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(JUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 440, 420, -1));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(153, 0, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_management_system/button (2).png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1870, 10, -1, -1));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 650, -1, -1));

        btnsSignin.setBackground(new java.awt.Color(255, 255, 255));
        btnsSignin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnsSignin.setForeground(new java.awt.Color(0, 0, 0));
        btnsSignin.setText("Sign in");
        btnsSignin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsSigninActionPerformed(evt);
            }
        });
        getContentPane().add(btnsSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 650, -1, -1));

        jLabelShow_Password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelShow_Password.setForeground(new java.awt.Color(255, 255, 255));
        jLabelShow_Password.setText("Show Password");
        jLabelShow_Password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelShow_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelShow_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jLabelShow_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 580, -1, -1));

        JPassword.setBackground(new java.awt.Color(255, 255, 255));
        JPassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(JPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 530, 420, -1));

        GoBackbtn.setBackground(new java.awt.Color(255, 255, 255));
        GoBackbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        GoBackbtn.setForeground(new java.awt.Color(0, 0, 0));
        GoBackbtn.setText("Go Back");
        GoBackbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GoBackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(GoBackbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 650, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_management_system/LOGIN&SIGNUPBG.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        JOptionPane.showMessageDialog(this, "Do you wish to exit the program?");
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Accounts acc = new Accounts();
        String genUse = acc.getEdcelUser();
        String genPass = acc.getEdcelPass();
        
        
        if (JUsername.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter your username");
        
        } else if (JPassword.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter your password");
           
        } else if (JUsername.getText().equals(genUse)&&JPassword.getText().equals(genPass)) {
           HomePage hp = new HomePage();
           hp.setLocationRelativeTo(null);
           hp.pack();
           hp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           hp.setVisible(true);
             
            
        } else if (JUsername.getText().equals(newUser)&&JPassword.getText().equals(newPass)) {
           HomePage hp = new HomePage();
           hp.setLocationRelativeTo(null);
           hp.pack();
           hp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           hp.setVisible(true);
           JOptionPane.showMessageDialog(this, "Login Successfully");
               
 
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Password and Username");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnsSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsSigninActionPerformed
        SignIn sg = new SignIn();
        sg.setLocationRelativeTo(null);
        sg.pack();
        sg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        sg.setVisible(true);
                     
    }//GEN-LAST:event_btnsSigninActionPerformed

    private void jLabelShow_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelShow_PasswordActionPerformed
        if(jLabelShow_Password.isSelected()) {
            JPassword.setEchoChar((char)0);
        } else {
            JPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jLabelShow_PasswordActionPerformed

    private void GoBackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackbtnActionPerformed
        // TODO add your handling code here
        StartHotel sh = new StartHotel();
        sh.setLocationRelativeTo(null);
        sh.pack();
        sh.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        sh.setVisible(true);
                      
    }//GEN-LAST:event_GoBackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBackbtn;
    private javax.swing.JPasswordField JPassword;
    private javax.swing.JTextField JUsername;
    private javax.swing.JLabel btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnsSignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox jLabelShow_Password;
    // End of variables declaration//GEN-END:variables
}
