/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_management_system;


import projects.InsertUpdateDelete;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import projects.select;
import projects.*;
import java.sql.PreparedStatement;


/**
 *
 * @author USER
 */
public class ManageRoom extends javax.swing.JFrame {
  
    
    //Take Two
    
   // private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageRoom.class.getName());
    
    /**
     * Creates new form ManageRoom
     */
    public ManageRoom(){
        initComponents();
        this.setLocationRelativeTo(null);
       
        
        PreparedStatement pst = null;
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableManageRoom = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRoomNumber = new javax.swing.JTextField();
        btnAddRoomDetails = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        comboBedType = new javax.swing.JComboBox<>();
        comboRoomType = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Room");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 0, 351, 58));

        JTableManageRoom.setBackground(new java.awt.Color(204, 204, 204));
        JTableManageRoom.setForeground(new java.awt.Color(102, 102, 102));
        JTableManageRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Type", "Bed Type", "Price", "Status"
            }
        ));
        JTableManageRoom.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(JTableManageRoom);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 64, 1553, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 511, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Room Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 511, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bed Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 668, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 668, -1, -1));

        txtRoomNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtRoomNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtRoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 554, 332, -1));

        btnAddRoomDetails.setBackground(new java.awt.Color(100, 149, 237));
        btnAddRoomDetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddRoomDetails.setForeground(new java.awt.Color(240, 240, 240));
        btnAddRoomDetails.setText("Add Room Details");
        btnAddRoomDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddRoomDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddRoomDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 554, -1, -1));

        btnCancel.setBackground(new java.awt.Color(100, 149, 237));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(240, 240, 240));
        btnCancel.setText("Cancel");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(988, 699, -1, -1));

        txtPrice.setBackground(new java.awt.Color(204, 204, 204));
        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 699, 332, -1));

        comboBedType.setBackground(new java.awt.Color(204, 204, 204));
        comboBedType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboBedType.setForeground(new java.awt.Color(51, 51, 51));
        comboBedType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        comboBedType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBedTypeActionPerformed(evt);
            }
        });
        getContentPane().add(comboBedType, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 699, 332, -1));

        comboRoomType.setBackground(new java.awt.Color(204, 204, 204));
        comboRoomType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboRoomType.setForeground(new java.awt.Color(51, 51, 51));
        comboRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));
        getContentPane().add(comboRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 554, 332, -1));

        jPanel1.setBackground(new java.awt.Color(40, 50, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRoomDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomDetailsActionPerformed
        
       
       /* String RoomNumber = txtRoomNumber.getText();
        String RoomType = (String)comboRoomType.getSelectedItem();
        String Bed = (String)comboBedType.getSelectedItem();
        String Price = txtPrice.getText();
        
        String Query = "insert into manageroom values('"+RoomNumber+"','"+RoomType+"','"+Bed+"','"+Price+"','Not Booked')";
        InsertUpdateDelete.setData(Query,"Successfully Updated");
        JOptionPane.showMessageDialog(this, "Please fill");
        setVisible(false);
        new ManageRoom().setVisible(true);
        */
       
       try {
       // Parse RoomNumber from text to int
       int RoomNumber = Integer.parseInt(txtRoomNumber.getText());

       // Get other values
       String RoomType = (String) comboRoomType.getSelectedItem();
       String Bed = (String) comboBedType.getSelectedItem();
       String Price = txtPrice.getText();

    // Build SQL query (RoomNumber is int, no quotes needed)
       String Query = "insert into manageroom values(" + RoomNumber + ",'" + RoomType + "','" + Bed + "','" + Price + "','Not Booked')";

    // Execute query
       InsertUpdateDelete.setData(Query, "Successfully Updated");
       setVisible(false);
       new ManageRoom().setVisible(true);

      } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Please fill up all");
}
    }//GEN-LAST:event_btnAddRoomDetailsActionPerformed
   
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
           HomePage hp = new HomePage();
           hp.setLocationRelativeTo(null);
           hp.pack();
           hp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           hp.setVisible(true);
           this.dispose();       
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs=select.getData("select *from manageroom");
        DefaultTableModel model = (DefaultTableModel)JTableManageRoom.getModel();
        try{
            while(rs.next()){
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
            }
            rs.close();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void comboBedTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBedTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBedTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageRoom().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableManageRoom;
    private javax.swing.JButton btnAddRoomDetails;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> comboBedType;
    private javax.swing.JComboBox<String> comboRoomType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRoomNumber;
    // End of variables declaration//GEN-END:variables
}
