/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel_management_system;

import javax.swing.JFrame;

/**
 *
 * @author USER
 */
public class StartHotel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StartHotel.class.getName());

    /**
     * Creates new form StartHotel
     */
    public StartHotel() {
        initComponents();
        this.setLocationRelativeTo(null); //place in center
       
       setExtendedState(JFrame.MAXIMIZED_BOTH);//fullscreen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startloginbutton = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startloginbutton.setBackground(new java.awt.Color(255, 255, 255));
        startloginbutton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        startloginbutton.setForeground(new java.awt.Color(0, 0, 0));
        startloginbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_management_system/enter.png"))); // NOI18N
        startloginbutton.setText("Start to Log In");
        startloginbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startloginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startloginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(startloginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 810, 390, 80));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_management_system/button.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1880, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_management_system/goldendawnBG.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void startloginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startloginbuttonActionPerformed
        // TODO add your handling code here:
        /*login abc = new login();
        abc.setLocationRelativeTo(null);
        abc.pack();
        abc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        abc.setVisible(true);
        */
        
        login li = new login();
        li.setVisible(true);
        li.pack();
        li.setLocationRelativeTo(null);
        li.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                   
    }//GEN-LAST:event_startloginbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StartHotel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton startloginbutton;
    // End of variables declaration//GEN-END:variables
}
